[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui-kit.workspace = true
sqlx.workspace = true
thiserror.workspace = true

shared = {path = "../shared"}
sidebar  =  {path ="../sidebar"}
settings  =  {path ="../settings"}
customers  =  {path ="../customers"}
projects  =  {path ="../projects"}
dotenv = "0.15.0"
tokio = { version = "1.53.1", features = ["full"]}
